//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Pedsim
{
    [Serializable]
    public class MetaMsg : Message
    {
        public const string k_RosMessageName = "pedsim_msgs/Meta";
        public override string RosMessageName => k_RosMessageName;

        //  Meta information about the current running nodes and parameters
        public Std.StringMsg[] nodes;
        public Diagnostic.KeyValueMsg[] @params;

        public MetaMsg()
        {
            this.nodes = new Std.StringMsg[0];
            this.@params = new Diagnostic.KeyValueMsg[0];
        }

        public MetaMsg(Std.StringMsg[] nodes, Diagnostic.KeyValueMsg[] @params)
        {
            this.nodes = nodes;
            this.@params = @params;
        }

        public static MetaMsg Deserialize(MessageDeserializer deserializer) => new MetaMsg(deserializer);

        private MetaMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.nodes, Std.StringMsg.Deserialize, deserializer.ReadLength());
            deserializer.Read(out this.@params, Diagnostic.KeyValueMsg.Deserialize, deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.WriteLength(this.nodes);
            serializer.Write(this.nodes);
            serializer.WriteLength(this.@params);
            serializer.Write(this.@params);
        }

        public override string ToString()
        {
            return "MetaMsg: " +
            "\nnodes: " + System.String.Join(", ", nodes.ToList()) +
            "\n@params: " + System.String.Join(", ", @params.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
